"use client";

import React, { useState, useEffect, FormEvent, ChangeEvent, useMemo, useCallback } from 'react';
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle, CardFooter } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogClose } from "@/components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Checkbox } from "@/components/ui/checkbox";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { Calendar } from "@/components/ui/calendar";
import { CalendarIcon, PlusCircle, Edit, Trash2, BookOpenText, Loader2, UploadCloud, Download, FileSpreadsheet, Search, ArrowUpDown, ChevronsLeft, ChevronLeft, ChevronRight, ChevronsRight, ListPlus, XCircle, Eye, Zap } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { Switch } from '@/components/ui/switch';
import type { Curriculum, Program, Course } from '@/types/entities';
import { curriculumService } from '@/lib/api/curriculum';
import { programService } from '@/lib/api/programs';
import { courseService } from '@/lib/api/courses';
import { format, parseISO } from 'date-fns';
import { cn } from "@/lib/utils";

type CurriculumStatus = 'draft' | 'active' | 'archived';
const CURRICULUM_STATUS_OPTIONS: { value: CurriculumStatus, label: string }[] = [
    { value: "draft", label: "Draft" },
    { value: "active", label: "Active" },
    { value: "archived", label: "Archived" },
];

type SortField = keyof Curriculum | 'programName' | 'none';
type SortDirection = 'asc' | 'desc';

const ITEMS_PER_PAGE_OPTIONS = [5, 10, 20, 50];

export default function CurriculumManagementPage() {
  const [curricula, setCurricula] = useState<Curriculum[]>([]);
  const [programs, setPrograms] = useState<Program[]>([]);
  const [allCourses, setAllCourses] = useState<Course[]>([]);

  const [isLoading, setIsLoading] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [isDialogOpen, setIsDialogOpen] = useState(false);
  const [isViewDialogOpen, setIsViewDialogOpen] = useState(false);
  const [currentCurriculum, setCurrentCurriculum] = useState<Partial<Curriculum> | null>(null);
  const [viewCurriculum, setViewCurriculum] = useState<Curriculum | null>(null);

  // Form state for Curriculum
  const [formProgramId, setFormProgramId] = useState<string>('');
  const [formVersion, setFormVersion] = useState('');
  const [formEffectiveDate, setFormEffectiveDate] = useState<Date | undefined>(new Date());
  const [formStatus, setFormStatus] = useState<CurriculumStatus>('draft');
  const [formCourses, setFormCourses] = useState<Curriculum['courses']>([]);
  const [isAutoGenerated, setIsAutoGenerated] = useState<boolean>(false);
  
  // Available courses for the selected program
  const [availableCourses, setAvailableCourses] = useState<Course[]>([]);

  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const [searchTerm, setSearchTerm] = useState(''); // Search by version or program name
  const [filterProgramVal, setFilterProgramVal] = useState<string>('all');
  const [filterStatusVal, setFilterStatusVal] = useState<CurriculumStatus | 'all'>('all');
  const [sortField, setSortField] = useState<SortField>('effectiveDate');
  const [sortDirection, setSortDirection] = useState<SortDirection>('desc');
  const [selectedCurriculumIds, setSelectedCurriculumIds] = useState<string[]>([]);

  const [currentPage, setCurrentPage] = useState(1);
  const [itemsPerPage, setItemsPerPage] = useState(ITEMS_PER_PAGE_OPTIONS[1]);

  const { toast } = useToast();

  const fetchInitialData = useCallback(async () => {
    setIsLoading(true);
    try {
      const [curriculaData, programsData, coursesData] = await Promise.all([
        curriculumService.getAllCurricula(),
        programService.getAllPrograms(),
        courseService.getAllCourses(),
      ]);
      setCurricula(curriculaData);
      setPrograms(programsData);
      setAllCourses(coursesData);

      if (programsData.length > 0 && !formProgramId) {
        setFormProgramId(programsData[0].id);
      }
    } catch {
      toast({ variant: "destructive", title: "Error", description: "Could not load initial data." });
    }
    setIsLoading(false);
  }, [toast, formProgramId]);

  useEffect(() => {
    fetchInitialData();
  }, [fetchInitialData]);

  useEffect(() => {
    if (formProgramId) {
      loadAvailableCourses(formProgramId);
    }
  }, [formProgramId]);

  const resetForm = () => {
    setFormProgramId(programs.length > 0 ? programs[0].id : '');
    setFormVersion('');
    setFormEffectiveDate(new Date());
    setFormStatus('draft');
    setFormCourses([]);
    setCurrentCurriculum(null);
    setIsAutoGenerated(false);
    setAvailableCourses([]);
  };

  const handleEdit = (curriculum: Curriculum) => {
    setCurrentCurriculum(curriculum);
    setFormProgramId(curriculum.programId);
    setFormVersion(curriculum.version);
    setFormEffectiveDate(curriculum.effectiveDate ? parseISO(curriculum.effectiveDate) : undefined);
    setFormStatus(curriculum.status);
    setFormCourses([...curriculum.courses]);
    setIsAutoGenerated(curriculum.isAutoGenerated || false);
    loadAvailableCourses(curriculum.programId);
    setIsDialogOpen(true);
  };

  const loadAvailableCourses = async (programId: string) => {
    try {
      const courses = await curriculumService.getCoursesByProgram(programId);
      setAvailableCourses(courses);
    } catch (error) {
      console.error('Failed to load courses:', error);
      toast({ variant: "destructive", title: "Error", description: "Failed to load courses for program." });
    }
  };

  const handleAutoGenerate = async () => {
    if (!formProgramId || !formVersion.trim() || !formEffectiveDate) {
      toast({ variant: "destructive", title: "Validation Error", description: "Program, Version, and Effective Date are required for auto-generation." });
      return;
    }

    setIsSubmitting(true);
    try {
      const result = await curriculumService.autoGenerateCurriculum(
        formProgramId,
        formVersion.trim(),
        format(formEffectiveDate, "yyyy-MM-dd")
      );
      
      // Auto-generation creates the curriculum directly, so refresh the list and close dialog
      await fetchInitialData();
      setIsDialogOpen(false);
      resetForm();
      toast({ 
        title: "Auto-Generated Successfully", 
        description: (result as any).message || `Generated curriculum with ${result.courses.length} courses.`
      });
    } catch (error: any) {
      if (error.message && error.message.includes('Try version name:')) {
        // Extract suggested version from error message
        const suggestedMatch = error.message.match(/'([^']+)'/g);
        if (suggestedMatch && suggestedMatch.length >= 2) {
          const suggestedVersion = suggestedMatch[1].replace(/'/g, '');
          setFormVersion(suggestedVersion);
          toast({ 
            variant: "default", 
            title: "Version Conflict", 
            description: `Updated version to: ${suggestedVersion}. Click Auto-Generate again.`
          });
        } else {
          toast({ variant: "destructive", title: "Version Conflict", description: error.message });
        }
      } else {
        toast({ variant: "destructive", title: "Auto-Generation Failed", description: error.message });
      }
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleSmartAutoGenerateAll = async () => {
    setIsSubmitting(true);
    try {
      const result = await curriculumService.autoGenerateAllCurricula();
      
      await fetchInitialData();
      toast({ 
        title: "🚀 Smart Generation Completed!", 
        description: `Generated ${result.summary.totalCurriculaGenerated} curricula for ${result.summary.programsProcessed} programs with transition logic.`
      });
      
      // Show detailed results
      console.log('Smart Curriculum Generation Results:', result);
    } catch (error: any) {
      toast({ variant: "destructive", title: "Smart Generation Failed", description: error.message });
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleView = (curriculum: Curriculum) => {
    setViewCurriculum(curriculum);
    setIsViewDialogOpen(true);
  };

  const handleAddNew = () => {
    if (programs.length === 0) {
      toast({ variant: "destructive", title: "Cannot Add", description: "No programs available. Please create programs first." });
      return;
    }
    resetForm();
    setIsDialogOpen(true);
  };

  const handleDelete = async (curriculumId: string) => {
    setIsSubmitting(true);
    try {
      await curriculumService.deleteCurriculum(curriculumId);
      await fetchInitialData();
      setSelectedCurriculumIds(prev => prev.filter(id => id !== curriculumId));
      toast({ title: "Curriculum Deleted", description: "Successfully deleted." });
    } catch (error) {
      toast({ variant: "destructive", title: "Delete Failed", description: (error as Error).message });
    }
    setIsSubmitting(false);
  };
  
  const handleToggleCourseActive = (courseId: string) => {
    setFormCourses(prev => prev.map(fc => 
      fc.courseId === courseId 
        ? { ...fc, isActive: !fc.isActive }
        : fc
    ));
  };

  const handleUpdateCourseOverride = (courseId: string, field: 'customSemester' | 'isCustomElective', value: number | boolean | undefined) => {
    setFormCourses(prev => prev.map(fc => {
      if (fc.courseId === courseId) {
        const updated = { ...fc, [field]: value };
        // Update legacy fields when overrides change
        if (field === 'customSemester' && typeof value === 'number') {
          updated.semester = value;
        }
        if (field === 'isCustomElective' && typeof value === 'boolean') {
          updated.isElective = value;
        }
        return updated;
      }
      return fc;
    }));
  };


  const handleSubmit = async (event: FormEvent) => {
    event.preventDefault();
    if (!formProgramId || !formVersion.trim() || !formEffectiveDate) {
      toast({ variant: "destructive", title: "Validation Error", description: "Program, Version, and Effective Date are required."});
      return;
    }
    if (formCourses.length === 0) {
        toast({ variant: "destructive", title: "Validation Error", description: "A curriculum must have at least one course."});
        return;
    }

    setIsSubmitting(true);
    const curriculumData: Omit<Curriculum, 'id' | 'createdAt' | 'updatedAt'> = {
      programId: formProgramId,
      version: formVersion.trim(),
      effectiveDate: format(formEffectiveDate, "yyyy-MM-dd"),
      status: formStatus,
      courses: formCourses,
      isAutoGenerated: isAutoGenerated,
    };

    try {
      if (currentCurriculum && currentCurriculum.id) {
        await curriculumService.updateCurriculum(currentCurriculum.id, curriculumData);
        toast({ title: "Curriculum Updated", description: "Successfully updated." });
      } else {
        await curriculumService.createCurriculum(curriculumData);
        toast({ title: "Curriculum Created", description: "Successfully created." });
      }
      await fetchInitialData();
      setIsDialogOpen(false);
      resetForm();
    } catch (error) {
      toast({ variant: "destructive", title: "Save Failed", description: (error as Error).message });
    } finally {
      setIsSubmitting(false);
    }
  };
  
  const handleFileChange = (event: ChangeEvent<HTMLInputElement>) => setSelectedFile(event.target.files?.[0] || null);
  
  const handleImportCurricula = async () => {
    if (!selectedFile) {
      toast({ variant: "destructive", title: "Import Error", description: "Please select a CSV file." });
      return;
    }
    if (programs.length === 0 || allCourses.length === 0) {
      toast({ variant: "destructive", title: "Import Error", description: "Programs or Courses data not loaded. Cannot map IDs." });
      return;
    }
    setIsSubmitting(true);
    try {
      const result = await curriculumService.importCurricula(selectedFile, programs, allCourses);
      await fetchInitialData();
      toast({ title: "Import Successful", description: `${result.newCount} curricula added, ${result.updatedCount} updated. Skipped: ${result.skippedCount}` });
      if(result.errors && result.errors.length > 0){
          result.errors.slice(0,3).forEach((err: unknown) => {
            const error = err as { row?: number; message?: string };
            toast({variant: "default", title: `Import Warning (Row ${error.row || 'unknown'})`, description: error.message || 'Unknown error', duration: 7000});
          });
      }
    } catch (error: unknown) {
      const errorMessage = error instanceof Error ? error.message : "Could not process CSV.";
      toast({ variant: "destructive", title: "Import Failed", description: errorMessage });
    } finally {
      setIsSubmitting(false); setSelectedFile(null);
      const fileInput = document.getElementById('csvImportCurriculum') as HTMLInputElement;
      if (fileInput) fileInput.value = '';
    }
  };

  const handleExportCurricula = () => {
    if (filteredAndSortedCurricula.length === 0) {
      toast({ title: "No Data", description: "No curricula to export." });
      return;
    }
    const header = ['id', 'programId', 'programCode', 'programName', 'version', 'effectiveDate', 'status', 'courseId', 'courseSubcode', 'courseName', 'semester', 'isElective'];
    const csvRows: string[] = [header.join(',')];
    filteredAndSortedCurricula.forEach(curr => {
        const prog = programs.find(p => p.id === curr.programId);
        curr.courses.forEach(cc => {
            const course = allCourses.find(c => c.id === cc.courseId);
            csvRows.push([
                curr.id, curr.programId, `"${prog?.code || ''}"`, `"${prog?.name || ''}"`,
                curr.version, curr.effectiveDate, curr.status,
                cc.courseId, `"${course?.subcode || ''}"`, `"${course?.subjectName || ''}"`,
                cc.semester, cc.isElective
            ].join(','));
        });
    });
    const csvString = csvRows.join('\r\n');
    const blob = new Blob([csvString], { type: 'text/csv;charset=utf-8;' });
    const link = document.createElement("a");
    link.href = URL.createObjectURL(blob);
    link.download = "curricula_export.csv";
    document.body.appendChild(link); link.click(); document.body.removeChild(link);
    toast({ title: "Export Successful", description: "Curricula exported." });
  };

  const handleDownloadSampleCsv = () => {
    const sampleCsvContent = `id,programId,programCode,version,effectiveDate,status,courseId,courseSubcode,semester,isElective
curr_1,prog_dce_gpp,DCE,1.0,2024-07-01,active,course_cs101_dce_gpp,CS101,1,false
curr_1,prog_dce_gpp,DCE,1.0,2024-07-01,active,course_math1_gen_gpp,MA101,1,false
curr_2,prog_dme_gpp,DME,2.1,2025-01-01,draft,course_me101_dme_gpp,ME101,1,false
`;
    const blob = new Blob([sampleCsvContent], { type: 'text/csv;charset=utf-8;' });
    const link = document.createElement("a");
    link.href = URL.createObjectURL(blob);
    link.download = "sample_curricula_import.csv";
    document.body.appendChild(link); link.click(); document.body.removeChild(link);
    toast({ title: "Sample CSV Downloaded" });
  };

  const handleSort = (field: SortField) => {
    if (sortField === field) setSortDirection(prev => prev === 'asc' ? 'desc' : 'asc');
    else { setSortField(field); setSortDirection('asc'); }
    setCurrentPage(1);
  };

  const filteredAndSortedCurricula = useMemo(() => {
    let result = [...curricula];
    if (searchTerm) {
        result = result.filter(c => 
            c.version.toLowerCase().includes(searchTerm.toLowerCase()) ||
            programs.find(p => p.id === c.programId)?.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
            programs.find(p => p.id === c.programId)?.code.toLowerCase().includes(searchTerm.toLowerCase())
        );
    }
    if (filterProgramVal !== 'all') result = result.filter(c => c.programId === filterProgramVal);
    if (filterStatusVal !== 'all') result = result.filter(c => c.status === filterStatusVal);

    if (sortField !== 'none') {
      result.sort((a, b) => {
        let valA: unknown = a[sortField as keyof Curriculum];
        let valB: unknown = b[sortField as keyof Curriculum];
        if(sortField === 'programName'){
            valA = programs.find(p => p.id === a.programId)?.name || '';
            valB = programs.find(p => p.id === b.programId)?.name || '';
        }
        if (valA === undefined || valA === null) return sortDirection === 'asc' ? 1 : -1;
        if (valB === undefined || valB === null) return sortDirection === 'asc' ? -1 : 1;
        if (typeof valA === 'string' && typeof valB === 'string') return sortDirection === 'asc' ? valA.localeCompare(valB) : valB.localeCompare(valA);
        if (typeof valA === 'number' && typeof valB === 'number') return sortDirection === 'asc' ? valA - valB : valB - valA;
        if (sortField === 'effectiveDate') {
          const dateA = valA && typeof valA === 'string' ? new Date(valA).getTime() : 0;
          const dateB = valB && typeof valB === 'string' ? new Date(valB).getTime() : 0;
          return sortDirection === 'asc' ? dateA - dateB : dateB - dateA;
        }
        return 0;
      });
    }
    return result;
  }, [curricula, searchTerm, filterProgramVal, filterStatusVal, sortField, sortDirection, programs]);

  const totalPages = Math.ceil(filteredAndSortedCurricula.length / itemsPerPage);
  const paginatedCurricula = useMemo(() => {
    const startIndex = (currentPage - 1) * itemsPerPage;
    return filteredAndSortedCurricula.slice(startIndex, startIndex + itemsPerPage);
  }, [filteredAndSortedCurricula, currentPage, itemsPerPage]);

  useEffect(() => { setCurrentPage(1); }, [searchTerm, filterProgramVal, filterStatusVal, itemsPerPage]);

  const handleSelectAll = (checked: boolean | 'indeterminate') => setSelectedCurriculumIds(checked === true ? paginatedCurricula.map(c => c.id) : []);
  const handleSelectCurriculum = (id: string, checked: boolean) => setSelectedCurriculumIds(prev => checked ? [...prev, id] : prev.filter(i => i !== id));
  
  const handleDeleteSelected = async () => {
    if(selectedCurriculumIds.length === 0) {
      toast({variant: "destructive", title: "No Selection", description: "Please select curricula to delete."});
      return;
    }
    setIsSubmitting(true);
    try {
      for(const id of selectedCurriculumIds) await curriculumService.deleteCurriculum(id);
      await fetchInitialData();
      toast({title: "Deleted", description: `${selectedCurriculumIds.length} curricula deleted.`});
      setSelectedCurriculumIds([]);
    } catch (error) {
      toast({variant: "destructive", title: "Delete Failed", description: (error as Error).message});
    }
    setIsSubmitting(false);
  };
  
  const isAllSelectedOnPage = paginatedCurricula.length > 0 && paginatedCurricula.every(c => selectedCurriculumIds.includes(c.id));
  const isSomeSelectedOnPage = paginatedCurricula.some(c => selectedCurriculumIds.includes(c.id)) && !isAllSelectedOnPage;

  if (isLoading) return <div className="flex justify-center items-center h-screen"><Loader2 className="h-10 w-10 animate-spin text-primary" /></div>;

  const SortableTableHeader = ({ field, label }: { field: SortField; label: string }) => (
    <TableHead onClick={() => handleSort(field)} className="cursor-pointer hover:bg-muted/50">
      <div className="flex items-center gap-2">{label}{sortField === field && (sortDirection === 'asc' ? <ArrowUpDown className="h-4 w-4 opacity-50 scale-y-[-1]" /> : <ArrowUpDown className="h-4 w-4 opacity-50" />)}{sortField !== field && <ArrowUpDown className="h-4 w-4 opacity-20" />}</div>
    </TableHead>
  );

  return (
    <div className="space-y-8">
      <Card className="shadow-xl">
        <CardHeader className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
          <div>
            <CardTitle className="text-2xl font-bold text-primary flex items-center gap-2"><BookOpenText className="h-6 w-6" />Curriculum Management</CardTitle>
            <CardDescription>Manage academic curricula, versions, and associated courses.</CardDescription>
          </div>
          <div className="flex flex-col sm:flex-row gap-2 w-full sm:w-auto">
            <Button 
              onClick={handleSmartAutoGenerateAll} 
              className="w-full sm:w-auto bg-gradient-to-r from-purple-600 to-blue-600 hover:from-purple-700 hover:to-blue-700" 
              disabled={isSubmitting}
            >
              {isSubmitting ? <Loader2 className="mr-2 h-5 w-5 animate-spin" /> : <Zap className="mr-2 h-5 w-5" />}
              Smart Generate All
            </Button>
            <Button onClick={handleAddNew} className="w-full sm:w-auto" disabled={programs.length === 0}><PlusCircle className="mr-2 h-5 w-5" /> New Curriculum</Button>
            <Button onClick={handleExportCurricula} variant="outline" className="w-full sm:w-auto"><Download className="mr-2 h-5 w-5" /> Export CSV</Button>
          </div>
        </CardHeader>
        <CardContent>
          <div className="mb-6 p-4 border rounded-lg space-y-4 bg-gradient-to-r from-purple-50 to-blue-50 dark:from-purple-900/20 dark:to-blue-900/20 border-purple-200 dark:border-purple-800">
            <h3 className="text-lg font-medium flex items-center gap-2">
              <Zap className="h-5 w-5 text-purple-600"/>
              Smart Curriculum Generation
            </h3>
            <div className="text-sm text-muted-foreground space-y-2">
              <p>🧠 <strong>Intelligent Auto-Generation:</strong> Creates curricula with progressive semester rollout logic</p>
              <ul className="list-disc list-inside ml-4 space-y-1">
                <li><strong>5G (DI*):</strong> Regular Sem 1-2 (2024-25) + Sem 3-4 (2025-26) | 5G-C2D starting 2025-26</li>
                <li><strong>4G (COGC-2021):</strong> Regular Sem 1-2 (2021-22) + Sem 3-4 (2022-23) + Sem 5-6 (2023-24) | 4G-ICT delayed + 4G-C2D starting 2022-23</li>
                <li><strong>1G, 2G, 3G (Archived):</strong> Legacy curricula with distinct subject code patterns (6-digit, 2-prefix, 3-prefix)</li>
              </ul>
              <p className="text-xs">💡 Five curriculum generations: 1G → 2G → 3G → 4G (COGC-2021) → 5G (Latest) with progressive rollouts</p>
            </div>
          </div>

          <div className="mb-6 p-4 border rounded-lg space-y-4 dark:border-gray-700">
            <h3 className="text-lg font-medium flex items-center gap-2"><UploadCloud className="h-5 w-5 text-primary"/>Import Curricula from CSV</h3>
            <div className="flex flex-col sm:flex-row gap-2 items-center">
              <Input type="file" id="csvImportCurriculum" accept=".csv" onChange={handleFileChange} className="flex-grow" disabled={isSubmitting} />
              <Button onClick={handleImportCurricula} disabled={isSubmitting || !selectedFile} className="w-full sm:w-auto">{isSubmitting && selectedFile ? <Loader2 className="mr-2 h-4 w-4 animate-spin"/> : <UploadCloud className="mr-2 h-4 w-4"/>} Import</Button>
            </div>
            <div className="flex items-center gap-2">
                <Button onClick={handleDownloadSampleCsv} variant="link" size="sm" className="px-0 text-primary"><FileSpreadsheet className="mr-1 h-4 w-4" /> Download Sample CSV</Button>
                <p className="text-xs text-muted-foreground">CSV fields: id, programId/Code, version, effectiveDate, status, courseId/Subcode, semester, isElective.</p>
            </div>
          </div>

          <div className="mb-6 grid grid-cols-1 sm:grid-cols-3 gap-4 p-4 border rounded-lg dark:border-gray-700">
            <div><Label htmlFor="searchCurriculum">Search Version/Program</Label><div className="relative"><Input id="searchCurriculum" placeholder="Version, Prog. Name/Code..." value={searchTerm} onChange={(e) => setSearchTerm(e.target.value)} className="pr-8"/><Search className="absolute right-2 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" /></div></div>
            <div><Label htmlFor="filterProgCurriculum">Filter by Program</Label><Select value={filterProgramVal} onValueChange={setFilterProgramVal} disabled={programs.length === 0}><SelectTrigger><SelectValue placeholder="All Programs"/></SelectTrigger><SelectContent><SelectItem value="all">All Programs</SelectItem>{programs.map(p => <SelectItem key={p.id} value={p.id}>{p.name} ({p.code})</SelectItem>)}</SelectContent></Select></div>
            <div><Label htmlFor="filterStatusCurriculum">Filter by Status</Label><Select value={filterStatusVal} onValueChange={(value) => setFilterStatusVal(value as CurriculumStatus | 'all')}><SelectTrigger><SelectValue placeholder="All Statuses"/></SelectTrigger><SelectContent>{[{value: 'all', label: 'All Statuses'} as {value: CurriculumStatus | 'all', label: string}, ...CURRICULUM_STATUS_OPTIONS].map(opt => <SelectItem key={opt.value} value={opt.value}>{opt.label}</SelectItem>)}</SelectContent></Select></div>
          </div>

          {selectedCurriculumIds.length > 0 && (
             <div className="mb-4 flex items-center gap-2">
                <Button variant="destructive" onClick={handleDeleteSelected} disabled={isSubmitting}><Trash2 className="mr-2 h-4 w-4" /> Delete Selected ({selectedCurriculumIds.length})</Button>
                <span className="text-sm text-muted-foreground">{selectedCurriculumIds.length} curriculum/a selected.</span>
            </div>
          )}

          {/* Mobile View */}
          <div className="block lg:hidden space-y-3">
            {paginatedCurricula.map((curr) => (
              <Card key={curr.id} className="shadow-sm">
                <CardContent className="p-4">
                  <div className="flex items-start justify-between mb-3">
                    <div className="flex items-center gap-3 min-w-0 flex-1">
                      <Checkbox
                        checked={selectedCurriculumIds.includes(curr.id)}
                        onCheckedChange={(checked) => handleSelectCurriculum(curr.id, !!checked)}
                        aria-labelledby={`curriculum-name-mobile-${curr.id}`}
                      />
                      <div className="min-w-0 flex-1">
                        <h4 id={`curriculum-name-mobile-${curr.id}`} className="font-semibold text-sm leading-tight">
                          {programs.find(p => p.id === curr.programId)?.name || 'N/A'}
                        </h4>
                        <p className="text-xs text-muted-foreground">Version {curr.version}</p>
                      </div>
                    </div>
                    <span className={`px-2 py-1 text-xs font-semibold rounded-full whitespace-nowrap ${
                      curr.status === 'active' ? 'bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-300'
                      : curr.status === 'draft' ? 'bg-yellow-100 text-yellow-800 dark:bg-yellow-900 dark:text-yellow-300'
                      : 'bg-red-100 text-red-800 dark:bg-red-900 dark:text-red-300'
                    }`}>
                      {CURRICULUM_STATUS_OPTIONS.find(s => s.value === curr.status)?.label || curr.status}
                    </span>
                  </div>
                  
                  <div className="grid grid-cols-2 gap-y-2 text-xs mb-3">
                    <div>
                      <span className="text-muted-foreground">Effective Date:</span>
                      <p className="font-medium">{format(parseISO(curr.effectiveDate), "dd MMM yyyy")}</p>
                    </div>
                    <div>
                      <span className="text-muted-foreground">Courses:</span>
                      <p className="font-medium">{curr.courses.length} subjects</p>
                    </div>
                  </div>
                  
                  <div className="flex gap-2">
                    <Button variant="outline" size="sm" onClick={() => handleView(curr)} disabled={isSubmitting} className="flex-1 min-h-[40px]">
                      <Eye className="h-4 w-4 mr-1" /> View
                    </Button>
                    <Button variant="outline" size="sm" onClick={() => handleEdit(curr)} disabled={isSubmitting} className="flex-1 min-h-[40px]">
                      <Edit className="h-4 w-4 mr-1" /> Edit
                    </Button>
                    <Button variant="destructive" size="sm" onClick={() => handleDelete(curr.id)} disabled={isSubmitting} className="min-h-[40px]">
                      <Trash2 className="h-4 w-4" />
                    </Button>
                  </div>
                </CardContent>
              </Card>
            ))}
            {paginatedCurricula.length === 0 && (
              <Card className="shadow-sm">
                <CardContent className="p-8 text-center text-muted-foreground">
                  No curricula found. Try adjusting your search or filters, or add a new curriculum.
                </CardContent>
              </Card>
            )}
          </div>

          {/* Desktop Table View */}
          <div className="hidden lg:block">
            <div className="overflow-x-auto border rounded-lg">
              <Table>
                <TableHeader><TableRow>
                  <TableHead className="w-[50px]"><Checkbox checked={isAllSelectedOnPage || (paginatedCurricula.length > 0 && isSomeSelectedOnPage ? 'indeterminate' : false)} onCheckedChange={(val) => handleSelectAll(val as boolean | 'indeterminate')}/></TableHead>
                  <SortableTableHeader field="programName" label="Program" />
                  <SortableTableHeader field="version" label="Version" />
                  <SortableTableHeader field="effectiveDate" label="Effective Date" />
                  <TableHead>Courses</TableHead>
                  <SortableTableHeader field="status" label="Status" />
                  <TableHead className="text-right">Actions</TableHead>
                </TableRow></TableHeader>
                <TableBody>
                  {paginatedCurricula.map((curr) => (
                    <TableRow key={curr.id} data-state={selectedCurriculumIds.includes(curr.id) ? "selected" : undefined}>
                      <TableCell><Checkbox checked={selectedCurriculumIds.includes(curr.id)} onCheckedChange={(checked) => handleSelectCurriculum(curr.id, !!checked)}/></TableCell>
                      <TableCell>{programs.find(p=>p.id === curr.programId)?.name || 'N/A'}</TableCell>
                      <TableCell>{curr.version}</TableCell>
                      <TableCell>{format(parseISO(curr.effectiveDate), "dd MMM yyyy")}</TableCell>
                      <TableCell>{curr.courses.length}</TableCell>
                      <TableCell><span className={`px-2 py-1 text-xs font-semibold rounded-full ${curr.status === 'active' ? 'bg-green-100 text-green-800' : curr.status === 'draft' ? 'bg-yellow-100 text-yellow-800' : 'bg-red-100 text-red-800'}`}>{CURRICULUM_STATUS_OPTIONS.find(s=>s.value === curr.status)?.label || curr.status}</span></TableCell>
                      <TableCell className="text-right space-x-2"><Button variant="outline" size="icon" onClick={() => handleView(curr)} disabled={isSubmitting}><Eye className="h-4 w-4" /></Button><Button variant="outline" size="icon" onClick={() => handleEdit(curr)} disabled={isSubmitting}><Edit className="h-4 w-4" /></Button><Button variant="destructive" size="icon" onClick={() => handleDelete(curr.id)} disabled={isSubmitting}><Trash2 className="h-4 w-4" /></Button></TableCell>
                    </TableRow>
                  ))}
                  {paginatedCurricula.length === 0 && <TableRow><TableCell colSpan={7} className="text-center text-muted-foreground py-8">No curricula found.</TableCell></TableRow>}
                </TableBody>
              </Table>
            </div>
          </div>
        </CardContent>
        <CardFooter className="flex flex-col sm:flex-row items-center justify-between gap-4 py-4">
            <div className="text-sm text-muted-foreground">Showing {paginatedCurricula.length > 0 ? Math.min((currentPage -1) * itemsPerPage + 1, filteredAndSortedCurricula.length): 0} to {Math.min(currentPage * itemsPerPage, filteredAndSortedCurricula.length)} of {filteredAndSortedCurricula.length} curricula.</div>
            <div className="flex items-center gap-2">
                <Select value={String(itemsPerPage)} onValueChange={(value) => {setItemsPerPage(Number(value)); setCurrentPage(1);}}><SelectTrigger className="w-[70px] h-8 text-xs"><SelectValue /></SelectTrigger><SelectContent side="top">{ITEMS_PER_PAGE_OPTIONS.map(sz => <SelectItem key={sz} value={String(sz)} className="text-xs">{sz}</SelectItem>)}</SelectContent></Select>
                <span className="text-sm text-muted-foreground">Page {currentPage} of {totalPages > 0 ? totalPages : 1}</span>
                <div className="flex items-center gap-1">
                    <Button variant="outline" size="icon" className="h-8 w-8" onClick={() => setCurrentPage(1)} disabled={currentPage === 1}><ChevronsLeft className="h-4 w-4" /></Button>
                    <Button variant="outline" size="icon" className="h-8 w-8" onClick={() => setCurrentPage(p => Math.max(1, p - 1))} disabled={currentPage === 1}><ChevronLeft className="h-4 w-4" /></Button>
                    <Button variant="outline" size="icon" className="h-8 w-8" onClick={() => setCurrentPage(p => Math.min(totalPages, p + 1))} disabled={currentPage === totalPages || totalPages === 0}><ChevronRight className="h-4 w-4" /></Button>
                    <Button variant="outline" size="icon" className="h-8 w-8" onClick={() => setCurrentPage(totalPages)} disabled={currentPage === totalPages || totalPages === 0}><ChevronsRight className="h-4 w-4" /></Button>
                </div>
            </div>
        </CardFooter>
      </Card>

      <Dialog open={isDialogOpen} onOpenChange={(isOpen) => { setIsDialogOpen(isOpen); if (!isOpen) resetForm(); }}>
        <DialogContent className="sm:max-w-3xl max-h-[90vh] flex flex-col">
          <DialogHeader><DialogTitle>{currentCurriculum?.id ? "Edit Curriculum" : "New Curriculum"}</DialogTitle><DialogDescription>Define curriculum details and assign courses.</DialogDescription></DialogHeader>
          <form id="curriculumForm" onSubmit={handleSubmit} className="space-y-4 py-2 overflow-y-auto flex-grow">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div><Label htmlFor="currProgramId">Program *</Label><Select value={formProgramId} onValueChange={setFormProgramId} required disabled={isSubmitting || programs.length === 0}><SelectTrigger><SelectValue placeholder="Select Program"/></SelectTrigger><SelectContent>{programs.map(p => <SelectItem key={p.id} value={p.id}>{p.name} ({p.code})</SelectItem>)}</SelectContent></Select></div>
                <div><Label htmlFor="currVersion">Version *</Label><Input id="currVersion" value={formVersion} onChange={e => setFormVersion(e.target.value)} placeholder="e.g., 1.0, 2024-A" required disabled={isSubmitting}/></div>
                <div><Label htmlFor="currEffectiveDate">Effective Date *</Label><Popover><PopoverTrigger asChild><Button variant="outline" className={cn("w-full justify-start", !formEffectiveDate && "text-muted-foreground")} disabled={isSubmitting}><CalendarIcon className="mr-2 h-4 w-4" />{formEffectiveDate ? format(formEffectiveDate, "PPP") : <span>Pick date</span>}</Button></PopoverTrigger><PopoverContent className="w-auto p-0"><Calendar mode="single" selected={formEffectiveDate} onSelect={setFormEffectiveDate} initialFocus/></PopoverContent></Popover></div>
                <div><Label htmlFor="currStatus">Status *</Label><Select value={formStatus} onValueChange={val => setFormStatus(val as CurriculumStatus)} required disabled={isSubmitting}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{CURRICULUM_STATUS_OPTIONS.map(s => <SelectItem key={s.value} value={s.value}>{s.label}</SelectItem>)}</SelectContent></Select></div>
            </div>

            <div className="pt-4 border-t mt-4 dark:border-gray-700">
                <div className="flex items-center justify-between mb-3">
                    <h4 className="text-md font-semibold">Curriculum Courses</h4>
                    <Button 
                        type="button" 
                        onClick={handleAutoGenerate} 
                        disabled={isSubmitting || !formProgramId || !formVersion.trim() || !formEffectiveDate}
                        variant="secondary"
                        size="sm"
                    >
                        {isSubmitting ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <PlusCircle className="mr-2 h-4 w-4" />}
                        Auto-Generate from Program
                    </Button>
                </div>
                
                {isAutoGenerated && (
                    <div className="mb-3 p-2 bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800 rounded-md">
                        <p className="text-sm text-blue-800 dark:text-blue-200">
                            📚 Auto-generated curriculum based on available courses for this program. 
                            You can fine-tune course settings below.
                        </p>
                    </div>
                )}
                
                <div className="mt-3 max-h-64 overflow-y-auto">
                    {formCourses.length === 0 ? (
                        <div className="text-center py-8 text-muted-foreground">
                            <BookOpenText className="mx-auto h-12 w-12 mb-2 opacity-50" />
                            <p className="text-sm">No courses in curriculum yet.</p>
                            <p className="text-xs mt-1">Use "Auto-Generate" to populate from program courses.</p>
                        </div>
                    ) : (
                        <Table className="text-xs">
                            <TableHeader>
                                <TableRow>
                                    <TableHead className="w-[40px]">Active</TableHead>
                                    <TableHead>Course</TableHead>
                                    <TableHead>Semester</TableHead>
                                    <TableHead>Type</TableHead>
                                    <TableHead>Override</TableHead>
                                </TableRow>
                            </TableHeader>
                            <TableBody>
                                {formCourses.map((fc, idx) => {
                                    const courseInfo = availableCourses.find(c => c.id === fc.courseId);
                                    return (
                                        <TableRow key={`${fc.courseId}-${idx}`} className={!fc.isActive ? 'opacity-50' : ''}>
                                            <TableCell className="py-2">
                                                <Checkbox 
                                                    checked={fc.isActive !== false} 
                                                    onCheckedChange={() => handleToggleCourseActive(fc.courseId)}
                                                />
                                            </TableCell>
                                            <TableCell className="py-2">
                                                <div>
                                                    <div className="font-medium">{courseInfo?.subjectName || fc.courseId}</div>
                                                    <div className="text-muted-foreground text-xs">{courseInfo?.subcode}</div>
                                                </div>
                                            </TableCell>
                                            <TableCell className="py-2">
                                                <Input 
                                                    type="number" 
                                                    value={fc.semester || ''} 
                                                    onChange={(e) => handleUpdateCourseOverride(fc.courseId, 'customSemester', Number(e.target.value) || undefined)}
                                                    className="w-16 h-8"
                                                    min="1" 
                                                    max="12"
                                                />
                                            </TableCell>
                                            <TableCell className="py-2">
                                                <Switch 
                                                    checked={fc.isElective || false}
                                                    onCheckedChange={(checked) => handleUpdateCourseOverride(fc.courseId, 'isCustomElective', checked)}
                                                />
                                                <span className="ml-2 text-xs text-muted-foreground">
                                                    {fc.isElective ? 'Elective' : 'Core'}
                                                </span>
                                            </TableCell>
                                            <TableCell className="py-2 text-xs text-muted-foreground">
                                                {(fc.customSemester && fc.customSemester !== courseInfo?.semester) || 
                                                 (fc.isCustomElective !== undefined && fc.isCustomElective !== courseInfo?.isElective) ? 
                                                 'Modified' : 'Default'}
                                            </TableCell>
                                        </TableRow>
                                    );
                                })}
                            </TableBody>
                        </Table>
                    )}
                </div>
            </div>
          </form>
          <DialogFooter className="pt-4 border-t mt-auto dark:border-gray-700">
            <DialogClose asChild><Button type="button" variant="outline" disabled={isSubmitting}>Cancel</Button></DialogClose>
            <Button type="submit" form="curriculumForm" disabled={isSubmitting}>{isSubmitting && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}{currentCurriculum?.id ? "Save Changes" : "Create Curriculum"}</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Curriculum View Dialog */}
      <Dialog open={isViewDialogOpen} onOpenChange={setIsViewDialogOpen}>
        <DialogContent className="sm:max-w-5xl max-h-[90vh] flex flex-col">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <BookOpenText className="h-5 w-5" />
              Curriculum Details - {viewCurriculum?.version}
            </DialogTitle>
            <DialogDescription>
              {programs.find(p => p.id === viewCurriculum?.programId)?.name} • 
              Effective from {viewCurriculum ? format(parseISO(viewCurriculum.effectiveDate), "dd MMM yyyy") : ''} • 
              {viewCurriculum?.isAutoGenerated ? 'Auto-Generated' : 'Manual'} • 
              {viewCurriculum?.courses.length} courses
            </DialogDescription>
          </DialogHeader>
          
          <div className="flex-grow overflow-y-auto py-4">
            {viewCurriculum && (
              <CurriculumDetailsView 
                curriculum={viewCurriculum} 
                programs={programs} 
                allCourses={allCourses} 
              />
            )}
          </div>
          
          <DialogFooter className="pt-4 border-t">
            <DialogClose asChild>
              <Button variant="outline">Close</Button>
            </DialogClose>
            <Button onClick={() => {
              setIsViewDialogOpen(false);
              handleEdit(viewCurriculum!);
            }} className="gap-2">
              <Edit className="h-4 w-4" />
              Edit Curriculum
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}

// Curriculum Details View Component
interface CurriculumDetailsViewProps {
  curriculum: Curriculum;
  programs: Program[];
  allCourses: Course[];
}

function CurriculumDetailsView({ curriculum, programs, allCourses }: CurriculumDetailsViewProps) {
  const program = programs.find(p => p.id === curriculum.programId);
  
  // Group courses by semester
  const coursesBySemester = curriculum.courses.reduce((acc, currCourse) => {
    const semester = currCourse.semester;
    if (!acc[semester]) {
      acc[semester] = [];
    }
    acc[semester].push(currCourse);
    return acc;
  }, {} as Record<number, typeof curriculum.courses>);

  // Sort semesters
  const sortedSemesters = Object.keys(coursesBySemester)
    .map(Number)
    .sort((a, b) => a - b);

  // Calculate statistics
  const totalCourses = curriculum.courses.length;
  const electiveCourses = curriculum.courses.filter(c => c.isElective).length;
  const coreCourses = totalCourses - electiveCourses;
  const totalCredits = curriculum.courses.reduce((sum, currCourse) => {
    const course = allCourses.find(c => c.id === currCourse.courseId);
    return sum + (course?.credits || 0);
  }, 0);

  return (
    <div className="space-y-6">
      {/* Summary Cards */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <Card>
          <CardContent className="p-4">
            <div className="text-2xl font-bold text-blue-600">{totalCourses}</div>
            <div className="text-sm text-muted-foreground">Total Courses</div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4">
            <div className="text-2xl font-bold text-green-600">{coreCourses}</div>
            <div className="text-sm text-muted-foreground">Core Courses</div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4">
            <div className="text-2xl font-bold text-orange-600">{electiveCourses}</div>
            <div className="text-sm text-muted-foreground">Elective Courses</div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4">
            <div className="text-2xl font-bold text-purple-600">{totalCredits}</div>
            <div className="text-sm text-muted-foreground">Total Credits</div>
          </CardContent>
        </Card>
      </div>

      {/* Program Information */}
      <Card>
        <CardHeader>
          <CardTitle className="text-lg">Program Information</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <Label className="text-sm font-medium text-muted-foreground">Program Name</Label>
              <p className="text-base">{program?.name || 'Unknown Program'}</p>
            </div>
            <div>
              <Label className="text-sm font-medium text-muted-foreground">Program Code</Label>
              <p className="text-base">{program?.code || 'N/A'}</p>
            </div>
            <div>
              <Label className="text-sm font-medium text-muted-foreground">Curriculum Version</Label>
              <p className="text-base">{curriculum.version}</p>
            </div>
            <div>
              <Label className="text-sm font-medium text-muted-foreground">Effective Date</Label>
              <p className="text-base">{format(parseISO(curriculum.effectiveDate), "dd MMMM yyyy")}</p>
            </div>
            <div>
              <Label className="text-sm font-medium text-muted-foreground">Status</Label>
              <span className={`inline-block px-3 py-1 text-sm font-medium rounded-full ${
                curriculum.status === 'active' ? 'bg-green-100 text-green-800' : 
                curriculum.status === 'draft' ? 'bg-yellow-100 text-yellow-800' : 
                'bg-red-100 text-red-800'
              }`}>
                {curriculum.status.charAt(0).toUpperCase() + curriculum.status.slice(1)}
              </span>
            </div>
            <div>
              <Label className="text-sm font-medium text-muted-foreground">Creation Type</Label>
              <p className="text-base">{curriculum.isAutoGenerated ? 'Auto-Generated' : 'Manual'}</p>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Semester-wise Course Details */}
      <Card>
        <CardHeader>
          <CardTitle className="text-lg">Course Structure</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="space-y-6">
            {sortedSemesters.map(semester => (
              <div key={semester} className="border rounded-lg p-4">
                <h3 className="text-lg font-semibold mb-3 text-primary">
                  Semester {semester}
                  <span className="ml-2 text-sm font-normal text-muted-foreground">
                    ({coursesBySemester[semester].length} courses)
                  </span>
                </h3>
                
                <div className="grid gap-3">
                  {coursesBySemester[semester].map((currCourse, idx) => {
                    const course = allCourses.find(c => c.id === currCourse.courseId);
                    return (
                      <div key={`${currCourse.courseId}-${idx}`} 
                           className="flex items-center justify-between p-3 border rounded-md bg-muted/30">
                        <div className="flex-grow">
                          <div className="flex items-center gap-2">
                            <h4 className="font-medium">{course?.subjectName || currCourse.courseId}</h4>
                            <span className="px-2 py-1 text-xs rounded-full bg-blue-100 text-blue-800">
                              {course?.subcode}
                            </span>
                            {currCourse.isElective && (
                              <span className="px-2 py-1 text-xs rounded-full bg-orange-100 text-orange-800">
                                Elective
                              </span>
                            )}
                            {!currCourse.isActive && (
                              <span className="px-2 py-1 text-xs rounded-full bg-gray-100 text-gray-600">
                                Inactive
                              </span>
                            )}
                          </div>
                          <div className="text-sm text-muted-foreground mt-1">
                            {course?.lectureHours || 0}L + {course?.tutorialHours || 0}T + {course?.practicalHours || 0}P
                          </div>
                        </div>
                        <div className="text-right">
                          <div className="text-lg font-semibold">{course?.credits || 0}</div>
                          <div className="text-xs text-muted-foreground">Credits</div>
                        </div>
                      </div>
                    );
                  })}
                </div>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
