name: Deploy with LaTeX Caching

on:
  push:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image with cache
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.latex-optimized
        push: true
        tags: ghcr.io/${{ github.repository }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        # Use registry cache for LaTeX layers
        cache-from: |
          type=registry,ref=ghcr.io/${{ github.repository }}:buildcache
        cache-to: |
          type=registry,ref=ghcr.io/${{ github.repository }}:buildcache,mode=max

    - name: Deploy to production
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          cd /root/projects/studio
          git pull origin main
          # Pull cached image instead of rebuilding
          docker pull ghcr.io/${{ github.repository }}:latest
          # Tag for local use
          docker tag ghcr.io/${{ github.repository }}:latest studio:latest
          # Restart with new image
          docker compose down
          docker compose up -d
          # Cleanup old images
          docker image prune -f